name: "TFLint"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      working_directory:
        required: false
        type: string
        default: "."

jobs:
  tflint:
    name: "TFLint (${{ inputs.environment }})"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: TFLint Init
        run: tflint --init

      - name: TFLint Run
        run: |
          tflint \
            --format compact \
            --recursive

      - name: Upload TFLint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tflint-report-${{ inputs.environment }}
          path: ${{ inputs.working_directory }}/tflint-report.*
          if-no-files-found: ignore
          retention-days: 7
